# Generated by Django 5.1.4 on 2026-05-27 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NailApplicationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para ocultar este registro sin eliminarlo', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de desactivación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de aplicación de uñas',
                'verbose_name_plural': 'Tipos de aplicación de uñas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para ocultar este registro sin eliminarlo', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de desactivación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de servicio',
                'verbose_name_plural': 'Categorías de servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para ocultar este registro sin eliminarlo', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de desactivación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('nail', 'Uñas'), ('eyebrow', 'Cejas'), ('waxing', 'Depilación'), ('other', 'Otros')], db_index=True, default='nail', help_text='Clasificación fija: uñas, cejas, depilación u otros', max_length=20, verbose_name='Categoría principal')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Tiempo estimado del servicio', verbose_name='Duración (minutos)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en pesos colombianos (COP)', max_digits=10, verbose_name='Precio')),
                ('service_category', models.ForeignKey(blank=True, help_text='Categoría creada por el administrador (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory', verbose_name='Categoría personalizada')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='idx_service_category_active')],
            },
        ),
    ]
