# Generated by Django 5.1.4 on 2026-05-27 16:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre de la clienta')),
                ('content', models.TextField(verbose_name='Opinión')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='De 1 a 5 estrellas', verbose_name='Calificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
