# Generated by Django 5.1.4 on 2026-05-27 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para ocultar este registro sin eliminarlo', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de desactivación')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('is_primary', models.BooleanField(default=False, help_text='Solo una especialista puede ser la principal (Diana)', verbose_name='Especialista principal')),
                ('photo', models.ImageField(blank=True, help_text='Foto profesional del especialista', upload_to='specialists/', verbose_name='Foto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('services', models.ManyToManyField(blank=True, help_text='Seleccionar los servicios que este especialista puede realizar', to='services.service', verbose_name='Servicios que realiza')),
                ('user', models.OneToOneField(blank=True, help_text='Opcional: credenciales de acceso para el especialista', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
                'ordering': ['-is_primary', 'first_name'],
                'indexes': [models.Index(fields=['is_primary', 'is_active'], name='idx_specialist_primary_active')],
            },
        ),
    ]
