# Generated by Django 5.1.4 on 2026-05-27 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para ocultar este registro sin eliminarlo', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de desactivación')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('phone', models.CharField(db_index=True, help_text='Formato: +57 300 123 4567', max_length=20, unique=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Correo electrónico')),
                ('birth_date', models.DateField(blank=True, help_text='Para enviar saludos de cumpleaños', null=True, verbose_name='Fecha de nacimiento')),
                ('total_visits', models.PositiveIntegerField(default=0, help_text='Se incrementa automáticamente al completar una cita', verbose_name='Visitas totales')),
                ('last_visit_date', models.DateField(blank=True, help_text='Fecha de la última cita completada', null=True, verbose_name='Última visita')),
                ('notes', models.TextField(blank=True, help_text='Preferencias, alergias, observaciones importantes', verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Clienta',
                'verbose_name_plural': 'Clientas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='idx_client_active_created'), models.Index(fields=['last_visit_date'], name='idx_client_last_visit')],
            },
        ),
    ]
