# Generated by Django 5.1.4 on 2026-05-27 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('total_appointments', models.PositiveIntegerField(default=0, verbose_name='Total citas')),
                ('cancelled_count', models.PositiveIntegerField(default=0, verbose_name='Cancelaciones')),
                ('no_show_count', models.PositiveIntegerField(default=0, verbose_name='No asistencias')),
                ('completed_count', models.PositiveIntegerField(default=0, verbose_name='Completadas')),
                ('cancellation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de cancelación (%)')),
                ('cancelled_by_client', models.PositiveIntegerField(default=0, help_text='Cuántas cancelaciones fueron iniciadas por la clienta', verbose_name='Canceladas por clienta')),
                ('last_minute_cancellations', models.PositiveIntegerField(default=0, help_text='Cancelaciones con menos de 2 horas de anticipación', verbose_name='Cancelaciones de último minuto')),
            ],
            options={
                'verbose_name': 'Estadística de cancelación',
                'verbose_name_plural': 'Estadísticas de cancelación',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Fecha')),
                ('total_appointments', models.PositiveIntegerField(default=0, verbose_name='Total citas')),
                ('completed_appointments', models.PositiveIntegerField(default=0, verbose_name='Completadas')),
                ('cancelled_appointments', models.PositiveIntegerField(default=0, verbose_name='Canceladas')),
                ('no_show_appointments', models.PositiveIntegerField(default=0, verbose_name='No asistieron')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos del día')),
                ('new_clients', models.PositiveIntegerField(default=0, verbose_name='Clientas nuevas')),
                ('returning_clients', models.PositiveIntegerField(default=0, verbose_name='Clientas recurrentes')),
            ],
            options={
                'verbose_name': 'Resumen diario',
                'verbose_name_plural': 'Resúmenes diarios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('service_name', models.CharField(help_text='Nombre en el momento de la estadística (congelado)', max_length=200, verbose_name='Nombre del servicio')),
                ('total_bookings', models.PositiveIntegerField(default=0, verbose_name='Total reservas')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ingresos totales')),
                ('month', models.DateField(db_index=True, verbose_name='Mes')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='services.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Estadística de servicio',
                'verbose_name_plural': 'Estadísticas de servicios',
                'ordering': ['-month', '-total_bookings'],
                'indexes': [models.Index(fields=['month', 'total_bookings'], name='idx_servicestat_month_bookings')],
                'unique_together': {('service', 'month')},
            },
        ),
    ]
