# Generated by Django 5.1.4 on 2026-05-27 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para ocultar este registro sin eliminarlo', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de desactivación')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha de la cita')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En curso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No asistió')], db_index=True, default='pending', help_text='Estado actual en el ciclo de vida de la cita', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Instrucciones especiales, preferencias, etc.', verbose_name='Notas de la cita')),
                ('is_cancelled_by_client', models.BooleanField(default=False, help_text='Indica si la cancelación fue iniciada por la clienta', verbose_name='Cancelada por la clienta')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Razón por la que se canceló la cita', verbose_name='Motivo de cancelación')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Momento en que se confirmó la cita', null=True, verbose_name='Confirmada el')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Momento en que finalizó el servicio', null=True, verbose_name='Completada el')),
                ('client', models.ForeignKey(help_text='Clienta que recibe el servicio', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client', verbose_name='Clienta')),
                ('nail_application_type', models.ForeignKey(blank=True, help_text='Obligatorio si el servicio es de uñas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.nailapplicationtype', verbose_name='Tipo de aplicación de uñas')),
                ('rescheduled_from', models.ForeignKey(blank=True, help_text='Cita original que fue reagendada a esta nueva cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointment', verbose_name='Reagendada desde')),
                ('service', models.ForeignKey(help_text='Servicio contratado', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service', verbose_name='Servicio')),
                ('specialist', models.ForeignKey(help_text='Especialista que realiza el servicio', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='specialists.specialist', verbose_name='Especialista')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRescheduleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('old_date', models.DateField(verbose_name='Fecha anterior')),
                ('old_start_time', models.TimeField(verbose_name='Hora inicio anterior')),
                ('old_end_time', models.TimeField(verbose_name='Hora fin anterior')),
                ('new_date', models.DateField(verbose_name='Nueva fecha')),
                ('new_start_time', models.TimeField(verbose_name='Nueva hora inicio')),
                ('new_end_time', models.TimeField(verbose_name='Nueva hora fin')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('rescheduled_by', models.CharField(choices=[('admin', 'Administrador'), ('client', 'Clienta'), ('system', 'Sistema')], default='admin', max_length=50, verbose_name='Reagendada por')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_logs', to='appointments.appointment', verbose_name='Cita')),
            ],
            options={
                'verbose_name': 'Registro de reagendación',
                'verbose_name_plural': 'Registros de reagendación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'status'], name='idx_appointment_date_status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'date'], name='idx_appointment_client_date'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['specialist', 'date', 'status'], name='idx_appt_spec_date_status'),
        ),
    ]
