# Generated by Django 5.1.4 on 2026-05-27 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='specialists.specialist', verbose_name='Especialista')),
            ],
            options={
                'verbose_name': 'Descanso',
                'verbose_name_plural': 'Descansos',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['specialist', 'date'], name='idx_break_specialist_date')],
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='specialists.specialist', verbose_name='Especialista')),
            ],
            options={
                'verbose_name': 'Día libre',
                'verbose_name_plural': 'Días libres',
                'ordering': ['-date'],
                'unique_together': {('specialist', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para ocultar este registro sin eliminarlo', verbose_name='Activo')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de desactivación')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')], verbose_name='Día de la semana')),
                ('morning_start', models.TimeField(default='08:00', verbose_name='Inicio mañana')),
                ('morning_end', models.TimeField(default='12:00', verbose_name='Fin mañana')),
                ('afternoon_start', models.TimeField(default='13:00', verbose_name='Inicio tarde')),
                ('afternoon_end', models.TimeField(default='20:00', verbose_name='Fin tarde')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='specialists.specialist', verbose_name='Especialista')),
            ],
            options={
                'verbose_name': 'Horario laboral',
                'verbose_name_plural': 'Horarios laborales',
                'ordering': ['day_of_week'],
                'unique_together': {('specialist', 'day_of_week')},
            },
        ),
    ]
