# Generated by Django 5.1.4 on 2026-05-27 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('notification_type', models.CharField(choices=[('reminder', 'Recordatorio'), ('confirmation', 'Confirmación'), ('cancellation', 'Cancelación'), ('follow_up', 'Seguimiento')], db_index=True, default='reminder', help_text='Recordatorio, confirmación, cancelación o seguimiento', max_length=20, verbose_name='Tipo de notificación')),
                ('recipient_phone', models.CharField(help_text='Número al que se envió el mensaje (formato internacional)', max_length=20, verbose_name='Teléfono destino')),
                ('message', models.TextField(help_text='Contenido exacto del mensaje en el momento del envío', verbose_name='Mensaje enviado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20, verbose_name='Estado del envío')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='Momento en que debe enviarse la notificación', null=True, verbose_name='Programado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado el')),
                ('provider', models.CharField(blank=True, choices=[('meta', 'Meta Cloud API'), ('twilio', 'Twilio')], default='meta', help_text='Qué proveedor se usó para el envío', max_length=20, verbose_name='Proveedor')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', help_text='Canal usado: WhatsApp o SMS', max_length=20, verbose_name='Canal')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, help_text='Número de veces que se ha intentado enviar (máx 3)', verbose_name='Intentos realizados')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, editable=False, verbose_name='Máximo de intentos')),
                ('error_message', models.TextField(blank=True, help_text='Descripción del error si el envío falló', verbose_name='Mensaje de error')),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='ID devuelto por la API de WhatsApp para tracking', max_length=100, verbose_name='ID del mensaje en WhatsApp')),
                ('appointment', models.ForeignKey(help_text='Cita asociada a esta notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment', verbose_name='Cita')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['appointment', 'notification_type'], name='idx_notif_appointment_type'), models.Index(fields=['status', 'scheduled_at'], name='idx_notif_status_scheduled')],
            },
        ),
    ]
